name: Comment files in new release

on:
  pull_request:
    types: [opened, reopened, edited]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Write comment
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for changesets
        uses: andstor/file-existence-action@v1
        with:
          files: './.changesets/*-*-*.md'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn run build

      - name: Prefill comment
        run: echo "# Released packages\n\n" > comment.txt

      - name: Prepare comment
        run: find ./packages/(nextract|database-*) -maxdepth 0 -exec yarn --silent --cwd {} pack --filename {}/pack.tgz \; -exec mkdir -p {}/package  \; -exec tar zxvf {}/pack.tgz -C {}/package \; -exec tree {}/package/package > comment.txt \;

      - name: Print comment
        run: cat comment.txt

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: $(cat comment.txt)
